name: pkgcheck

# This will cancel running jobs once a new run is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  # Manually trigger the Action under Actions/pkgcheck
  workflow_dispatch:
  # Run on every push to main
  push:
    branches:
      - main

jobs:
  pkgcheck:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true

      # As cmdstanr is not yet on CRAN, configure the action to only install the
      # 'Depends' packages by default and then manually specify the 'Suggests'
      # packages that are needed for R CMD CHECK
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: NA
          extra-packages: |
            ape
            stan-dev/cmdstanr
            colorspace
            dplyr
            ggdist
            ggplot2
            knitr
            methods
            phangorn
            phaseR
            pkgdown
            posterior
            purrr
            rcmdcheck
            readr
            rlang
            rmarkdown
            stringr
            testthat
            tidyr
            withr

      - uses: ropensci-review-tools/pkgcheck-action@main
